name: AI Review

on:
  push:
    branches:
      - mbr/review_test
  pull_request:


# Cancel previous runs on this reference
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_application:
    name: AI Review with gh copilot extension
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_ai_code_review.yml@mbr/reusable_ai_code_review
