name: Swap functional tests

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - develop
  pull_request:

# Cancel previous runs on this reference
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  job_functional_tests:
    uses: LedgerHQ/app-exchange/.github/workflows/reusable_swap_functional_tests.yml@develop
    with:
      branch_for_solana: ${{ github.ref }}
      test_filter: '"SOL or sol or Solana or solana"'
